#!/usr/bin/env sh

# Simple script to download youtube video into m4a format to a directory
# Default directory: ~/Downloads/youtubedl

PROGRAM_NAME=jjdl

if [ "$1" == "" ]; then
    echo "Usage: $PROGRAM_NAME [OPTION]... [URL]..."
    echo "Try '$PROGRAM_NAME --help' for more information."
    exit 1
fi

mkdir -p ~/Downloads/youtubedl
cd ~/Downloads/youtubedl || exit 1
youtube-dl  -o "%(title)s.%(ext)s" -i --format m4a --embed-thumbnail --add-metadata $1
